version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: precast-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: precast_db
      POSTGRES_USER: precast_user
      POSTGRES_PASSWORD: precast_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U precast_user -d precast_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Server
  api:
    build: .
    container_name: precast-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=precast_db
      - DB_USER=precast_user
      - DB_PASSWORD=precast_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./precast.db:/app/precast.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  default:
    name: precast-network
